name: MLAKSDeployAML
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - tornado<6
  - nb_conda_kernels==2.1.0
  - ipywidgets==7.3.0
  - pandas>=0.23.3
  - scikit-learn>=0.19.1
  - pip:
    - urllib3==1.23
    - aiohttp>=3.3.2
    - nest_asyncio>=0.9.10
    - toolz>=0.9.0
    - tqdm>=4.23.4
    - azure-cli>=2.0.50
    - prompt_toolkit>=2.0.7
    - lightgbm>=2.1.2
    - papermill>=0.14.1
    - python-dotenv==0.10.1
    - azureml-sdk[notebooks]==1.0.33
